let g:togglepunct = [
      \['()', '[]', '{}'],
      \['""', "''", '``'],
      \['(', ')'],
      \['[', ']'],
      \['{', '}'],
      \['&&', '||'],
      \['++', '--'],
      \['<<<', '>>>'],
      \['<<', '>>'],
      \['<=', '>='],
      \['&&=', '||='],
      \['&=', '|='],
      \['+=', '-='],
      \['*=', '/='],
      \['===', '!=='],
      \['==', '!='],
      \['&', '|'],
      \['+', '-'],
      \['*', '/'],
      \['<', '>'],
      \]

let g:togglewords = [
      \['zero',  'one',  'two',  'three',  'four',  'five',  'six',  'seven',  'eight',  'nine',  'ten',
      \'eleven',  'twelve',  'thirteen', 'fourteen',  'fifteen',  'sixteen',  'seventeen',  'eighteen',  'nineteen'],
      \['import', 'export'],
      \['join', 'split'],
      \['enable', 'disable'],
      \['enabled', 'disabled'],
      \['end', 'begin'],
      \['on', 'off'],
      \['true', 'false'],
      \['yes', 'no'],
      \['get', 'set'],
      \['short', 'long'],
      \['absolute', 'relative'],
      \['high', 'low'],
      \['horizontal', 'vertical'],
      \['in', 'out'],
      \['inner', 'outer'],
      \['left', 'right'],
      \['top', 'bottom'],
      \['up', 'down'],
      \['forward', 'back'],
      \['black', 'gray', 'white'],
      \['dark', 'light'],
      \['join', 'split'],
      \['pop', 'push'],
      \['shift', 'unshift'],
      \['atan', 'tan'],
      \['ceil', 'floor'],
      \['cos', 'sin'],
      \['min', 'max'],
      \['minor', 'major'],
      \['copy', 'cut', 'paste'],
      \['keydown', 'keyup'],
      \['mousedown', 'mouseup'],
      \['mouseenter', 'mouseleave'],
      \['head', 'body'],
      \['header', 'footer'],
      \['ol', 'ul'],
      \['tr', 'td'],
      \['activate', 'deactivate'],
      \['add', 'remove'],
      \['background', 'foreground'],
      \['available', 'unavailable'],
      \['before', 'after'],
      \['client', 'server'],
      \['connect', 'disconnect'],
      \['connected', 'disconnected'],
      \['first', 'last'],
      \['from', 'to'],
      \['input', 'output'],
      \['install', 'uninstall'],
      \['key', 'value'],
      \['online', 'offline'],
      \['open', 'close'],
      \['parent', 'child'],
      \['positive', 'negative'],
      \['prefix', 'suffix'],
      \['previous', 'next'],
      \['public', 'private'],
      \['req', 'res'],
      \['request', 'response'],
      \['row', 'column'],
      \['show', 'hide'],
      \['source', 'destination'],
      \['start', 'stop'],
      \['valid', 'invalid'],
      \['visible', 'hidden'],
      \['valid', 'invalid'], 
      \['width', 'height'],
      \['x', 'y'],
      \['fu', 'endf'],
      \['fun', 'endfun'],
      \['function', 'endfunction'],
      \['if', 'endif'],
      \['for', 'endfor'],
      \['while', 'endwhile'],
      \['try', 'catch', 'throw', 'endtry'],
      \['function', 'endfunction'],
      \['fun', 'endfun'],
      \['noremap', 'nnoremap', 'vnoremap', 'xnoremap', 'inoremap', 'cnoremap'],
      \['map', 'nmap', 'vmap', 'xmap', 'imap', 'cmap'],
      \['silent', 'buffer', 'nowait'],
      \['if', 'endif', 'fi'],
      \['case', 'esac'],
      \['for', 'endfor', 'done'],
      \['lower', 'upper'],
      \['lowercase', 'uppercase'],
      \['try', 'catch', 'throw'],
      \['and', 'or', 'xor', 'not', 'nand'],
      \['win', 'lose'],
      \['malloc', 'calloc', 'free'],
      \['nan', 'inf'],
      \['red', 'orange', 'yellow',  'green', 'cyan', 'blue',  'purple', 'magenta'],
      \['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      \'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      \]


